### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by tuco5** [tuco5/blockspot.club#5]
#i18n
##Description
Add support for internationalization in an early stage.

## Tasks
- [x] Look for what technology is easier to set up.
- [x] Set up the project to have i18n support.
- [x] Give support for English and Spanish first.

**Comment by tuco5** [comment]
### Resolution:
This is the technology we are using [next-intl](https://next-intl-docs.vercel.app/)

### Implementation
The setup is complete for English and Spanish
